---
title: "IVs, DVs, What-the-V?!?"
logo: ../img/psu-logo.png
css: ../css/dna.css
bibliography: ../bib/psych_301.bib
csl: ../csl/apa_5th.csl
output: 
  html_document:
    theme: spacelab
    toc: yes
    toc_depth: 4
    toc_float: no
    code_folding: hide
---


```{css, echo=FALSE}
.spoiler {
  visibility: hidden;
}

.spoiler::before {
  visibility: visible;
  content: "This is the answer! Hover to reveal!"
}

.spoiler:hover {
  visibility: visible;
}

.spoiler:hover::before {
  display: none;
}
```

I'm not going to lie to you...when I was first learning the difference between
an IV and a DV it took a while to keep them straight. Throw into that mixture studies
that don't necessarily need either of them to exist and I was lost. Might as well throw
in the hat, right? Wrong! That's something Jean would say before I made her love
research methods and statistics!

It's OK to be confused by these terms. I always tell my colleagues and students that 75%
of psychological theory is psychologists debating the same things with different names.
Similarly, you will hear one hundred different ways to define IVs and DVs, but what
really matters is that definition that *you* think is the best way to remember and
differentiate them by. Here I present what helped/helps me differentiate between the
two, and my thought process when I can't decide which variable goes where in
theoretical space.

# Independent Variables
Your book describes an **independent variable** (IV) as one that is being manipulated by the
researchers. In other words, what is the researcher directly impacting when she or he is
conducting the study? In most regards this is a fair assessment of an IV.

However, IVs are not always manipulated by the researcher, and to think that they always
are is limiting to what you can consider a "true" IV. Take for example, "gender".
Perceived gender is often a variable of interst in scientific study. However, one
cannot simply "manipulate" gender at a whim. So does this not count as a true IV? Of
course not! Our definition of an IV needs to allow for potential variables of interest
that cannot be directly manipulated by the researcher.

## Examples of IVs
All right, let's take a look at a few examples. We'll start off with an example
close to my heart and move deeper into the realm of crazy DVs/IVs from there.

A long time ago I was a researcher in a human-animal bond lab. Since there is
rarely an interest in this type of research (though it certainly is worthy of study!)
I'll take a couple examples from this field so I don't steal ideas from anyone.

> A psychologist is interested in examining whether or not dogs obey their owner's
> commands when she or he is holding a treat vs. when she or he merely speaks the
> command. Average dog compliance is summed after 6 months of intervention.

**What is the IV?**: <i class="spoiler">Treat status: Does the owner have a treat?</i>

> A comparative psychologist is interested in examining Oxycontin levels in dogs
> when their tails are wagging vs. when they are not wagging. This psychologist
> takes samples of the "bonding hormone" Oxycontin when dogs' tails are wagging
> furiously vs. little-to-none. Average oxytocin levels are compared after six
> weeks of samples.

**What is the IV?**: <i class="spoiler">Tail wagging: is it wagging a lot or not very much?</i>

> A clinical psycholgist is curious about the effeciveness of coginitive behavioral therapy (CBT)
> on treatment of Cyclothymia. They team with a reserach university and randomly assign
> 100 potential clients to either receive CBT or receive traditional medication treatment only.
> After 8 weeks of treatment the team assesses how depressed clients are on Beck depression
> inventory.

**What is the IV?**: <i class="spoiler">Treatment: Whether the client was in the CBT or traditional treatment.</i>

> A social psychologist is interested in whether primates exhibt facial expressions similar to
> humans in situations that typically elicit disgust in humans. S/he partners with a zoo to
> setup an experiment in which the primates' normal food rations are given to them as normal,
> except they are either under-ripe, just right, or rotten.

**What is the IV?**: <i class="spoiler">Fruit ripeness: Is the food just right?</i>

> A sports psychologist is intersted in examining the effect of referee calls on women's
> soccer player performence. S/he examines the amount of calls on player goals over the
> course of a one year period.

**What is the IV?**: <i class="spoiler">Correlational study! referre calls and goals are both variables of interst!</i>

> A school psycholigist wants to know if extended morning homeroom increases student performance
> on classes during the first half of the school day. S/he contacts schools within her/his school
> district to setup extended homeroom time for 1/3 of schools in the district, shortening homeroom
> classes for another 1/3, and leaving the homeroom as is for the other 1/3.

**What is the IV?**: <i class="spoiler">Homeroom time: extended, normal, or shortened.</i>

# Dependent Variables
Text.

## Examples of DVs
> A psychologist is interested in examining whether or not dogs obey their owner's
> commands when she or he is holding a treat vs. when she or he merely speaks the
> command.

**What is the DV**: 

# What about Correlational Studies?

# No IVs or DVs?

# Summary
OK, fine. That's a lot of text. You want the TLDR version. I'm not that
bitter about it. Here you go...

| **Variable** |                                                             **Questions to determine** |
|:-----------: |:-------------------------------------------------------------------------------------: |
|  Independent |  What's being manipulated? What's being measured but not an outcome measure? |
|    Dependent |  What is the researcher's primary interest? What are they measuring? |

***Disclaimer***: New and advanced studies are coming out all of the time. What one
considers an IV others may not. If you are unsure or are confused about what constitutes
an IV or DV, don't hesitate to ask your instructor!


