---
title: "Course Schedule: Supplemental Materials"
logo: img/psu-logo.png
css: css/dna.css
bib: bib/psych_301.bib
output: 
  html_document:
    theme: spacelab
    toc: yes
    toc_depth: 4
    toc_float: no
    code_folding: hide
---

```{r include = FALSE}
mon <- as.Date("2019-08-26")

advdate <- function(obj, adv) {
 tmon <- obj + 7*(adv-1)
 tsun <- obj + 6 + 7*(adv-1)
 tmon <- format(tmon, format="%B %d")
 tsun <- format(tsun, format="%B %d, %Y")
 tmp <- paste(tmon,"to",tsun)
 return(tmp)}
```


# Course Schedule
This is the landing page for the supplemental materials used in PSYCH 301. Main lesson assignments, schedule,
and homework can be found on the CANVAS page.

First, if you haven't already ready the course [Welcome letter](welcome.html), please do so! It provides some useful
information for the course.

After that, feel free to navigate to the appropriate supplemental lesson plan. I will be updating this as
on a rolling basis as the course progresses.

## Lesson 1: Introduction to Research
**`r advdate(mon, 1)`** \

1. [Why should I care about research?](lessons/important_research.html)

## Lesson 2: Hypothesis Generation
**`r advdate(mon, 2)`** \

1. [IV, DV, What-the-V!?](lessons/iv_dv_what.html) \
2. [What is a good research topic?](lessons/finding_research_topic.html)

## Lesson 3: Ethics in Research
**`r advdate(mon, 3)`**

## Lesson 4: Paper Writing
**`r advdate(mon, 4)`**

## Lesson 5: Measurement and Variables
**`r advdate(mon, 5)`**

## Lesson 6: Reliability and Validity
**`r advdate(mon, 6)`**

## Lesson 7: Surveys and Sampling
**`r advdate(mon, 7)`**

## Lesson 8: Hypothesis Testing and Inferential Statistics
**`r advdate(mon, 8)`**

## Lesson 9: One-way Experimental Design
**`r advdate(mon, 9)`**

## Lesson 10: Factorial Experimental Design
**`r advdate(mon, 10)`**

## Lesson 11: Correlational Design
**`r advdate(mon, 11)`**

## Lesson 12: Naturalistic Observation Methods
**`r advdate(mon, 12)`**

## Lesson 13: Internal and External Validity
**`r advdate(mon, 13)`**

## Break
**`r advdate(mon, 14)`**

## Final Research Proposal
**`r advdate(mon, 15)`**

## Lesson 14: Quasi-Experimental Design
**`r advdate(mon, 16)`**
